- name: Commit and Push
  env:
    PAT: ${{ secrets.GH_PAT }}
  run: |
    git config --global user.name 'github-actions'
    git config --global user.email 'github-actions@github.com'
    git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
    git add -A
    git commit -m "generate pacman contribution graph"
    git push
